projects:
  alzbyemer:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: 2jq7n6db5jf3dfxkltmnssmgau
      endpoints:
        prod: >-
          https://ztvijs2wkvei7agesrf7ycgsuq.appsync-api.us-west-2.amazonaws.com/graphql
